### ISSUE TITLE
Request: add {NOIA Network}

### ISSUE THREAD

**Issue by NojusLi** [Uniswap/tokenlists-org#189]
- [x] I understand that this is not the place to request token listing.
- [x] I have tested that my list is compatible by pasting the url into the `add a list` UI at `app.uniswap.org`.
- [x] I understand that filing an issue or adding liquidity does not guarantee addition to the token list website.
- [x] I will not ping the Discord about this listing request.

**Please provide the following information for your token.**
List url must be HTTPS, IPFS or ENS.

List Address: 
https://gateway.ipfs.io/ipns/tokens.uniswap.org
+
https://tokens.coingecko.com/uniswap/all.json
Symbol: NOIA
Contract: 0xfc858154c0b2c4a3323046fb505811f110ebda57
Decimals: 18

List Name:
Name: NOIA Network
Link to the official homepage of the list manager: https://noia.network

Logo Link: https://noia.network/assets/logo_b.svg

Uniswap Exchange Address of Token: https://uniswap.info/token/0xfc858154c0b2c4a3323046fb505811f110ebda57

**Comment by lorenzo8769** [comment]
New Smart Contract (Kucoin Hack)
Symbol: NOIA
Contract: 0xa8c8cfb141a3bb59fea1e2ea6b79b5ecbcd7b6ca
Decimals: 18

**Comment by callil** [comment]
Can you explain more about how your project is using token lists?

**Comment by lorenzo8769** [comment]
Hi @callil ,

We want our token to be listed on Uniswap (to find it more easily)

Here are the updated details:

**Uniswap Exchange Address of Token:**  => NEW
https://uniswap.info/token/0xa8c8cfb141a3bb59fea1e2ea6b79b5ecbcd7b6ca

**Uniswap Exchange Address of Token:**  => OLD to remove from your database
https://uniswap.info/token/0xfc858154c0b2c4a3323046fb505811f110ebda57

**New Smart Contract (because of Kucoin Hack)**
Symbol: NOIA
Contract: 0xa8c8cfb141a3bb59fea1e2ea6b79b5ecbcd7b6ca
Decimals: 18

**Logo Link:**
https://noia.network/assets/logo_b.svg

Thx

Laurent
Ambassador NOIA Network

**Comment by lorenzo8769** [comment]
@callil 
**Safe Source:**
https://medium.com/noia/kucoin-exchange-hack-update-fe8f49ca6393

**Comment by callil** [comment]
@lorenzo8769 getting a single token listed is not in the spirit of this project. You should seek to get your token added to another list.
